### ISSUE TITLE
Unable to run in geopackage file

### ISSUE THREAD

**Issue by GuillemHerrera** [eduard-kazakov/attributeBasedClustering#1]
First off all, thanks for this amazing plugin. It's really useful and fast.

I'm not able to run correctly the plugin based in a GeoPackage layer. Qgis throw me this error. 

`CRITICAL    BaseLayer : Error de OGR al crear el campo class: sqlite3_exec(ALTER TABLE "Barris_IERMB_Cleaned" ADD COLUMN "class" MEDIUMINT) failed: database is locked `

Seems like the plugin is not able to edit a geopackage database. 

I run correctly the plugin for the same layer in .shp format.

Thanks!

**Comment by eduard-kazakov** [comment]
Hi, Guillem!
Sorry for very long answering.
As i could see, new version of  plugin (2.2) works well with geopackages in latest versions of QGIS.

**Comment by GuillemHerrera** [comment]
Thanks Eduard for your plugin!
Great work!
