### ISSUE TITLE
"centroid" linkage method is missing

### ISSUE THREAD

**Issue by ttencate** [eduard-kazakov/attributeBasedClustering#3]
Hi, thanks for making this plugin! It's very useful.

One little thing is bothering me though: on the Hierarchical-2 tab, the Linkage method dropdown does not contain "centroid". All the other linkage functions of [`scipy.cluster.hierarchy.linkage`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html#scipy.cluster.hierarchy.linkage) are supported. Maybe just an oversight?

**Comment by eduard-kazakov** [comment]
Hi, Thomas, and thanks for your find! "centroid" method is added in new plugin version (2.2), together with the new functionality
