### ISSUE TITLE
Couldn't load plugin 'attributeBasedClustering' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by gumball850** [eduard-kazakov/attributeBasedClustering#5]
Hello,

I tried installing this plugin and received this error message as it was installing:

> Couldn't load plugin 'attributeBasedClustering' due to an error when calling its classFactory() method 
> 
> TypeError: 'QVariant' object is not subscriptable 
> Traceback (most recent call last):
>   File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "C:/Users/xxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\attributeBasedClustering\__init__.py", line 20, in classFactory
>     return AttributeBasedClustering(iface)
>   File "C:/Users/xxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\attributeBasedClustering\attribute_based_clustering.py", line 26, in __init__
>     locale = QSettings().value('locale/userLocale')[0:2]
> TypeError: 'QVariant' object is not subscriptable
> 
> 
> Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
> QGIS version: 3.16.16-Hannover Hannover, f5778a89df

**Comment by eduard-kazakov** [comment]
Should be fixed in 3.0
